module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.(spec|integration)\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    // Focus on core, implemented code paths
    'accounting/**/*.service.ts',
    'appointments/**/*.service.ts',
    'customers/**/*.service.ts',
    'day-closing/**/*.service.ts',
    'dashboard/**/*.service.ts',
    'employees/**/*.service.ts',
    'services/**/*.service.ts',
    // Controllers with strong coverage
    'accounting/**/*.controller.ts',
    'day-closing/**/*.controller.ts',
    'services/**/*.controller.ts',
    'health/**/*.controller.ts',
    // Exclusions
    '!**/*.spec.ts',
    '!**/*.integration.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/coverage/**',
    '!**/test/**',
    '!**/dto/**',
    '!**/*.dto.ts',
    '!**/*.module.ts',
    '!**/guards/**',
    '!**/middleware/**',
    '!**/middlewares/**',
    '!**/logger/**',
    '!**/backup/**',
    '!**/monitoring/**',
    '!**/homepage/**',
    '!**/throttler/**',
    '!**/sms/**',
    '!**/notifications/**',
    '!**/main.ts',
    '!**/prisma.service.ts',
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  coverageThreshold: {
    global: {
      statements: 75,
      branches: 50,
      functions: 70,
      lines: 75,
    },
  },
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
  },
  testTimeout: 30000,
  maxWorkers: 1, // Run tests sequentially to avoid database conflicts
  verbose: true,
};
