export const BARBER_APPOINTMENT_DEDUCTION_TOMAN = 200_000;
export const TOMAN_TO_RIAL = 10;
export const BARBER_APPOINTMENT_DEDUCTION_RIAL =
  BARBER_APPOINTMENT_DEDUCTION_TOMAN * TOMAN_TO_RIAL;

export const DEFAULT_COMMISSION_PERCENTAGE = 40;

export const EMPLOYEE_EXPENSE_CATEGORY_CODES = [
  'EMPLOYEE_WITHDRAWAL',
  'COMMISSION_SETTLEMENT',
  'SALARY_ADVANCE',
  'PAYROLL',
] as const;

export const COMMISSION_SETTLEMENT_SOURCE_TYPE = 'COMMISSION_SETTLEMENT';
